SYMBOL = "BTCUSDT"
INTERVAL = "15m"
BASE_URL = "https://fapi.binance.com"

START_DATE = "2025-01-01"
END_DATE = "2026-08-01"
STARTING_BALANCE = 1000.0

RISK_PER_TRADE = 0.005
FEE_RATE = 0.0005
SLIPPAGE_BPS = 2.0

EMA_FAST = 20
EMA_MID = 50
EMA_SLOW = 200
ATR_PERIOD = 14
ATR_STOP_MULTIPLIER = 1.5
BREAKOUT_LOOKBACK = 20
VOLUME_PERIOD = 20
VOLUME_MULTIPLIER = 1.20
RSI_PERIOD = 14
ADX_PERIOD = 14
ADX_MIN = 20

# === BREAKEVEN + TRAIL EXIT ===
# When price reaches entry + 0.5× risk distance, move stop to entry price
BREAKEVEN_R = 0.5

# Single hard target at 3R (no partial profit taking)
TP1_R = 3.0
TP1_CLOSE_FRACTION = 0.0
TP2_R = 3.0
TP2_CLOSE_FRACTION = 0.0

# Trailing stop starts ONLY after breakeven is hit
TRAIL_ATR_MULTIPLIER = 1.5

ENTRY_SCORE = 0

MAX_POSITIONS = 1
OOS_START = ""
OOS_END = ""
SAVE_CHART = True
